"""Initial migration - Entry model

Revision ID: 316ffd9bb981
Revises: 
Create Date: 2026-01-07 12:50:25.775559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316ffd9bb981'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entries')
    # ### end Alembic commands ###
