#cloud-config
# =============================================================================
# Nginx Static File Server
# =============================================================================
#
# Purpose: Serve static files (HTML, CSS, JS, images) directly from nginx
#
# Features:
# - Efficient static file serving with gzip compression
# - Browser caching headers for performance
# - Security headers
# - Custom error pages support
#
# Use cases:
# - Single-page applications (React, Vue, Angular builds)
# - Static websites (Hugo, Jekyll output)
# - CDN origin server
# - File downloads
#
# How it works:
# 1. Installs nginx
# 2. Creates web root directory with proper permissions
# 3. Configures nginx for static file serving
# 4. Enables gzip compression and caching
#
# Configuration:
# - Deploy static files to /var/www/html/
# - Replace 'adminuser' with your cloud provider's default SSH user
#
# =============================================================================
package_update: true
package_upgrade: true

packages:
  - nginx

write_files:
  - path: /etc/nginx/sites-available/static
    content: |
      server {
          listen 80 default_server;
          listen [::]:80 default_server;
          server_name _;

          # Document root for static files
          root /var/www/html;
          index index.html index.htm;

          # Gzip compression
          gzip on;
          gzip_vary on;
          gzip_min_length 1024;
          gzip_types text/plain text/css text/xml text/javascript
                     application/javascript application/json application/xml
                     application/rss+xml image/svg+xml;

          # Security headers
          add_header X-Frame-Options "SAMEORIGIN" always;
          add_header X-Content-Type-Options "nosniff" always;
          add_header X-XSS-Protection "1; mode=block" always;

          # Main location - serve static files
          location / {
              try_files $uri $uri/ =404;
          }

          # Cache static assets (CSS, JS, images)
          location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
              expires 30d;
              add_header Cache-Control "public, immutable";
          }

          # Cache HTML files (shorter duration)
          location ~* \.html$ {
              expires 1h;
              add_header Cache-Control "public, must-revalidate";
          }

          # Deny access to hidden files
          location ~ /\. {
              deny all;
          }
      }
    owner: root:root
    permissions: '0644'

runcmd:
  # Create web root directory
  - mkdir -p /var/www/html

  # Set permissions (replace 'adminuser' with your SSH user)
  # Owner: adminuser (for deployment via SCP)
  # Group: www-data (nginx worker process)
  - chown -R adminuser:www-data /var/www/html
  - chmod 755 /var/www/html

  # Create placeholder index page
  - |
    cat > /var/www/html/index.html << 'EOF'
    <!DOCTYPE html>
    <html>
    <head>
        <title>Static Server Ready</title>
        <style>
            body { font-family: system-ui, sans-serif; max-width: 600px; margin: 50px auto; padding: 20px; }
            h1 { color: #333; }
            code { background: #f4f4f4; padding: 2px 6px; border-radius: 3px; }
        </style>
    </head>
    <body>
        <h1>Static File Server Ready</h1>
        <p>Deploy your static files to <code>/var/www/html/</code></p>
        <p>Example: <code>scp -r ./dist/* user@server:/var/www/html/</code></p>
    </body>
    </html>
    EOF

  # Enable site and disable default
  - ln -sf /etc/nginx/sites-available/static /etc/nginx/sites-enabled/static
  - rm -f /etc/nginx/sites-enabled/default

  # Reload nginx
  - systemctl reload nginx
